### ISSUE TITLE
Translation not escaping dollar sign (potentially other special symbols too) and this creates issue in preg_replace later in the code

### ISSUE THREAD

**Issue by GeorgeBotsev** [OnTheGoSystems/wpml-page-builders#9]
https://github.com/OnTheGoSystems/wpml-page-builders/blob/8c7031eb0d973992ae240b1fa0d283260a207db4/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php#L59
https://github.com/OnTheGoSystems/wpml-page-builders/blob/8c7031eb0d973992ae240b1fa0d283260a207db4/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php#L85
https://github.com/OnTheGoSystems/wpml-page-builders/blob/8c7031eb0d973992ae240b1fa0d283260a207db4/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php#L91
I am adding these as a pointer to where I have made modifications
The problem here is that we use the string without checking if it contains special symbol like dollar sign ($)
In example if you have the string: "$1,500" - in the translation you will receive ",500" here because of not sanitizing and escaping the dollar sign.
I used this code / or similar to do the magic:
`
            $translation = addslashes($translation);
            $translation = str_replace(['\\','$'], ['', '\$'], $translation);
`
This might not be 100% efficient, but seems to fix the problem if inserted in the appropriate mentioned places for the appropriate variables.

**Comment by andreasciamanna** [comment]
I think the correct function to escape the charachters is [`preg_quote`](http://php.net/manual/en/function.preg-quote.php):

> **preg_quote()** takes str and puts a backslash in front of every character that is part of the regular expression syntax. This is useful if you have a run-time string that you need to match in some text and the string may contain special regex characters.

**Comment by strategio** [comment]
This should have been fixed with https://github.com/OnTheGoSystems/wpml-page-builders/pull/37, let's close this ticket.
